services:
  - type: web
    name: mindmate
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run mindmate_app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
